theme = "autumn_night" # "catppuccin_mocha"

[editor]
line-number = "relative"
scrolloff = 999
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"space" = { w = ":w", c = ":buffer-close" }
X = "extend_line_above"
C-x = [ "extend_to_line_bounds", "trim_selections" ]
C-h = [ ":buffer-previous" ]
C-l = [ ":buffer-next" ]

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
C-space = "completion"
