theme = "tokyonight"

[editor]
line-number = "relative"
scrolloff = 999
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { w = ":w", c = ":buffer-close" }

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode