theme = "gruvbox"

[editor]
bufferline = "multiple"
color-modes = true
line-number = "relative"
scrolloff = 999
terminal.command = "alacritty"
popup-border ="all"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
snippets = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
# "space" = { w = ":w", c = ":buffer-close" }
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
C-s = ":w"
C-x = ["extend_to_line_bounds", "trim_selections"]
M = [":buffer-previous"]
I = [":buffer-next"]
D = ["extend_to_line_end", "delete_selection"]
V = ["extend_to_line_end"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
w = ":w"
c = ":buffer-close"
Q = ":quit"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
C-space = "completion"
