[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }

[[language]]
name = "tsx"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }

# [[language]]
# name = "rust"
# auto-format = true
#
# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"
#
# [[language.debugger.templates]]
# name = "binary"
# request = "launch"
# [[language.debugger.templates.completion]]
# completion = "target/debug/blue_marble"
# name = "binary"
#
# [language.debugger.templates.args]
# program = "{0}"
# runInTerminal = true

[[language]]
name = "markdown"
auto-format = true
# language-servers = [{ command = "remark-language-server", args = ["--stdio"] }]
formatter = { command = 'npx', args = [
  "prettier",
  "-c",
  ".prettierrc",
  "--parser",
  "markdown",
] }

[[language]]
name = "css"
# language-servers = [{ command = "vscode-css-language-server", args = ["--stdio"] }]

[[language]]
name = "toml"
# language-servers = [{ command = "taplo", args = ["lsp", "stdio"] }]
auto-format = true
