[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"

[[language]]
name = "markdown"
auto-format = true
language-server = { command = "remark-language-server", args = ["--stdio"] }

[[language]]
name = "css"
language-server = { command = "vscode-css-language-server", args = ["--stdio"] }

[[language]]
name = "toml"
language-server = { command = "taplo" }
