[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }

[[language]]
name = "tsx"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }

[language-server.solargraph]
command = "solargraph"
args = ["stdio"]
config = { diagnostics = false, formatting = false }

[language-server.rubocop]
command = "rubocop"
args = ["--lsp", "--stderr", "--fail-level", "fatal"]
timeout = 3

[[language]]
name = "ruby"
language-servers = [
  "rubocop",
  { name = "solargraph", except-features = [
    "format",
    "diagnostics",
  ] },
]
auto-format = true

[language-server.tailwindcss-language-server]
command = "./node_modules/.bin/tailwindcss-language-server"
args = ["-vvv", "--stdio"]

[[language]]
language-servers = ["tailwindcss-language-server"]
name = "erb"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
# language-servers = [{ command = "remark-language-server", args = ["--stdio"] }]
formatter = { command = 'npx', args = [
  "prettier",
  "-c",
  ".prettierrc",
  "--parser",
  "markdown",
] }

[[language]]
name = "css"
# language-servers = [{ command = "vscode-css-language-server", args = ["--stdio"] }]

[[language]]
name = "toml"
# language-servers = [{ command = "taplo", args = ["lsp", "stdio"] }]
auto-format = true

[language-server.godot]
command = "nc"
args = ["localhost", "6005"]

[[language]]
name = "gdscript"
language-servers = ['godot']
formatter = { command = "git", args = ["stripspace"] }
auto-format = true

[[language]]
name = "rust"
auto-format = true

