alias la="ls -lah"
alias ll="ls -lh"
alias eiv='nvim $HOME/dotfiles/nvim/.config/nvim/init.vim'
alias dot='source $HOME/.zshrc'
alias hg="history 1 | grep "
alias otz='dmux -P flutter -s task_zen $PROJECTS_PATH/task_zen'
alias orc='dmux -P react -s jusbrasil-rc $PROJECTS_PATH/react-components'
alias odot='dmux -P dev -s dotfiles $HOME/dotfiles'
alias nr='npf run'
