# shellcheck shell=bash

# alias k="kubectl"
# alias ka="kubectl apply -f ."
alias ael="aws ec2 describe-instances"
alias aeln="aws ec2 describe-instances --query \"Reservations[].Instances[].Tags[?Key=='Name'].Value\" --output text"
alias c=clear
alias dcd="docker compose down -v"
alias dcu="docker compose up -d"
alias dot='source $HOME/.zshrc'
alias dv=devbox
alias dvg="devbox global"
alias dvs="devbox shell"
alias gss="git status"
alias h=hledger
alias hg="history 1 | grep"
alias kk="k9s"
alias kt="kitty --session ~/.config/kitty/startup.conf"
alias la="eza -la --icons"
alias ld=lazydocker
alias lg=lazygit
alias ll="eza -l --icons"
alias ln=lazynpm
alias p=pnpm
alias pi="pnpm install"
alias rm=trash
alias t=taskwarrior-tui
alias tw="~/code/judit/taskell.md"
alias v=nvim
alias yz=yazi
