# shellcheck shell=bash

function tree {
  br -c :pt "$@"
}

function short {
  curl -F"shorten=$1" https://0x0.st
}

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        rm -f "$cmd_file"
        return "$code"
    fi
}

function hc {
  habito checkin $1
  habito list
}

function reset-network {
  sudo modprobe -r r8168
  sudo modprobe r8168
}

pf() {
  set -f
  local PUEUE_TASKS="pueue status --json | jq -c '.tasks' | jq -r '.[] | \"\(.id | tostring | (\" \" * (2 - length)) + .) | \(.group) | \(.path[-15:]) | \(.status) | \(.command[-15:]) | \(.start[:19])\"'"
  local header="p:pause | s:start | r:restart | k:kill | l:log | f:follow | d:reload"

local bind="\
ctrl-p:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue pause > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-s:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue start > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-r:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue restart -ik > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-k:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue kill > /dev/null)+reload^$PUEUE_TASKS^,\
ctrl-l:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue log | less > /dev/tty),\
ctrl-f:execute-silent(echo {} | cut -d'|' -f1 | xargs pueue follow > /dev/tty),\
ctrl-d:reload^$PUEUE_TASKS^\
"

  echo $PUEUE_TASKS | sh | fzf --header "${header}" -m \
    --preview="echo {} | cut -d'|' -f1 | xargs pueue log | bat -l log --style=rule,numbers --color=always -r ':200'" \
    --bind="$bind"
  set +f
}

curl-time() {
curl -w @- -o /dev/null -s "$@" <<'EOF'
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
EOF
}

function mk {
  mkdir -p $1
  cd $1
}

_rtx_hook() {
  trap -- '' SIGINT;
  eval "$("/opt/homebrew/bin/rtx" hook-env -s zsh)";
  trap - SIGINT;
}
typeset -ag precmd_functions;
if [[ -z "${precmd_functions[(r)_rtx_hook]+1}" ]]; then
  precmd_functions=( _rtx_hook ${precmd_functions[@]} )
fi
typeset -ag chpwd_functions;
if [[ -z "${chpwd_functions[(r)_rtx_hook]+1}" ]]; then
  chpwd_functions=( _rtx_hook ${chpwd_functions[@]} )
fi

function delete_secret() {
    if [ $# -ne 1 ]; then
        echo "Usage: delete_secret <secret_id>"
        return 1
    fi

    local secret_id="$1"
    local region="us-east-1"

    aws secretsmanager delete-secret --secret-id "$secret_id" --force-delete-without-recovery --region "$region"
}

function delete_secrets_for_branch() {
    local branch_name="$1"
    local secret_templates=(
        "eng-api-$branch_name-codebuild-elastic-admin-key"
        "eng-api-$branch_name-codebuild-cognito-client-secret"
        "eng-api-$branch_name-codebuild-postgres-password"
    )

    for secret in "${secret_templates[@]}"; do
        delete_secret "$secret"
    done
}

function destroy_stack() {
    local branch_name="$1"

    pulumi stack select "motrix/env/$branch_name" --cwd infra/projects/env 2>/dev/null || true
    pulumi config set branch_name "$branch_name" --cwd infra/projects/env
    pulumi config set githubConnectionArn arn:aws:codestar-connections:us-east-1:786966036727:connection/5e705a79-3e07-4ea2-ae69-d4a25570ea4e  --cwd infra/projects/env
    pulumi config set coreReference dev --cwd infra/projects/env
    pulumi config set coreReference dev --cwd infra/projects/env
    pulumi destroy --yes --cwd infra/projects/env
}
