# shellcheck shell=bash

function tree {
  br -c :pt "$@"
}

function short {
  curl -F"shorten=$1" https://0x0.st
}

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        rm -f "$cmd_file"
        return "$code"
    fi
}

function regen-npm-rc {
  echo -n "Generation npmrc for token $GITHUB_ACCESS_TOKEN \n\n"
  access_token="$( echo -n "$GITHUB_USERNAME:$GITHUB_ACCESS_TOKEN" | base64)"

  echo -n "_auth=$access_token"
}

function hc {
  habito checkin $1
  habito list
}

function reset-network {
  sudo modprobe -r r8168
  sudo modprobe r8168
}
