#!/usr/bin/env sh

limelight -m config width            4
limelight -m config radius           10
limelight -m config placement        exterior
limelight -m config active_color     0x504287f5
limelight -m config normal_color     0x00000000

echo "limelight configuration loaded.."
