require('config.closetag')
require('config.colorscheme')
require('config.completion')
require('config.galaxyline')
require('config.gina')
require('config.lspsaga')
require('config.nvim-tree')
require('config.treesitter')
-- require('config.metals')
