layouts:
    - tall
    - fullscreen

mod1:
    - control
    - command
mod2:
    - shift
    - control
    - command

relaunch-amethyst:
    mod: mod2
    key: x
    
focus-cw:
    mod: mod1
    key: k
    
focus-ccw:
    mod: mod1
    key: j
    
swap-main:
    mod: mod2
    key: i

shrink-main:
  mod: mod2
  key: h

expand-main:
  mod: mod2
  key: l

mouse-follows-focus: false
focus-follows-mouse: false

window-margins: true
window-margin-size: 10