return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "diff",
      "dockerfile",
      "eex",
      "elixir",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "html",
      "hurl",
      "http",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "jsonc",
      "json5",
      "just",
      "lua",
      "markdown",
      "mermaid",
      "norg",
      "prisma",
      "regex",
      "sql",
      "toml",
      "tsx",
      "typescript",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<c-x>",
        node_incremental = "<c-x>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
  },
}
